services:
  postgres:
    image: postgres:16-alpine
    container_name: magna-escrita
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: magna_escrita
    volumes:
      - magna_escrita_pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: magna-escrita-redis
    restart: unless-stopped
    ports:
      - '6379:6379'

volumes:
  magna_escrita_pg_data:

