export interface ApiError {
  statusCode: number;
  key: ErrorKeys;
  message: string;
  path: string;
  timestamp: string;
  requestId?: string;
  errors?: Array<{ field: string; messages: string[] }>;
}

export enum ErrorKeys {
  BAD_REQUEST_MISSING_GOOGLE_AUTH_TOKEN = 'BAD_REQUEST_MISSING_GOOGLE_AUTH_TOKEN',
  UNAUTHORIZED_INVALID_GOOGLE_CREDENTIALS = 'UNAUTHORIZED_INVALID_GOOGLE_CREDENTIALS',
  UNAUTHORIZED_INVALID_TOKEN = 'UNAUTHORIZED_INVALID_TOKEN',
  UNAUTHORIZED_USER_NOT_FOUND = 'UNAUTHORIZED_USER_NOT_FOUND',
  UNAUTHORIZED_BACKOFFICE_ACCESS = 'UNAUTHORIZED_BACKOFFICE_ACCESS',
  UNAUTHORIZED_INVALID_WEBHOOK_SIGNATURE = 'UNAUTHORIZED_INVALID_WEBHOOK_SIGNATURE',

  FORBIDDEN_MISSING_AUTH_TOKEN = 'FORBIDDEN_MISSING_AUTH_TOKEN',
  FORBIDDEN_INSUFFICIENT_PERMISSIONS = 'FORBIDDEN_INSUFFICIENT_PERMISSIONS',

  NOT_FOUND_BOOK_NOT_FOUND = 'NOT_FOUND_BOOK_NOT_FOUND',
  NOT_FOUND_ORDER = 'NOT_FOUND_ORDER',
  NOT_FOUND_SCHOOL = 'NOT_FOUND_SCHOOL',
  NOT_FOUND_UNIT = 'NOT_FOUND_UNIT',

  BAD_REQUEST_GRADE_NAME = 'BAD_REQUEST_GRADE_NAME',
  BAD_REQUEST_STUDENTS = 'BAD_REQUEST_STUDENTS',
  BAD_REQUEST_MULTIPLE_UNITS_ACCESS = 'BAD_REQUEST_MULTIPLE_UNITS_ACCESS',
  BAD_REQUEST_NO_VALID_UNIT_ID = 'BAD_REQUEST_NO_VALID_UNIT_ID',

  UNAUTHORIZED_USER_NO_ACCESS_TO_UNIT = 'UNAUTHORIZED_USER_NO_ACCESS_TO_UNIT',

  CREATE_PIX_ORDER_FAILED = 'CREATE_PIX_ORDER_FAILED',
  CREATE_CARD_ORDER_FAILED = 'CREATE_CARD_ORDER_FAILED',

  BAD_REQUEST_GRADE_NAME_ALREADY_EXISTS = 'BAD_REQUEST_GRADE_NAME_ALREADY_EXISTS',
  NOT_FOUND_GRADE = 'NOT_FOUND_GRADE',

  HTTP_ERROR = 'HTTP_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',

  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}
