export interface ApiError {
  statusCode: number;
  key: ErrorKeys;
  message: string;
  path: string;
  timestamp: string;
  requestId?: string;
  errors?: Array<{ field: string; messages: string[] }>;
}

export enum ErrorKeys {
  BAD_REQUEST_MISSING_GOOGLE_AUTH_TOKEN = 'BAD_REQUEST_MISSING_GOOGLE_AUTH_TOKEN',
  UNAUTHORIZED_INVALID_GOOGLE_CREDENTIALS = 'UNAUTHORIZED_INVALID_GOOGLE_CREDENTIALS',
  UNAUTHORIZED_INVALID_TOKEN = 'UNAUTHORIZED_INVALID_TOKEN',
  UNAUTHORIZED_USER_NOT_FOUND = 'UNAUTHORIZED_USER_NOT_FOUND',
  UNAUTHORIZED_BACKOFFICE_ACCESS = 'UNAUTHORIZED_BACKOFFICE_ACCESS',
  UNAUTHORIZED_INVALID_WEBHOOK_SIGNATURE = 'UNAUTHORIZED_INVALID_WEBHOOK_SIGNATURE',
  UNAUTHORIZED_CREATE_SCHOOL = 'UNAUTHORIZED_CREATE_SCHOOL',
  UNAUTHORIZED_USER_IS_NOT_ADMIN = 'UNAUTHORIZED_USER_IS_NOT_ADMIN',

  FORBIDDEN_MISSING_AUTH_TOKEN = 'FORBIDDEN_MISSING_AUTH_TOKEN',
  FORBIDDEN_INSUFFICIENT_PERMISSIONS = 'FORBIDDEN_INSUFFICIENT_PERMISSIONS',
  FORBIDDEN_BOOK_READY = 'FORBIDDEN_BOOK_READY',
  FORBIDDEN_USER_NOT_ADMIN = 'FORBIDDEN_USER_NOT_ADMIN',

  NOT_FOUND_BOOK_NOT_FOUND = 'NOT_FOUND_BOOK_NOT_FOUND',
  NOT_FOUND_ORDER = 'NOT_FOUND_ORDER',
  NOT_FOUND_SCHOOL = 'NOT_FOUND_SCHOOL',
  NOT_FOUND_UNIT = 'NOT_FOUND_UNIT',
  NOT_FOUND_EVENT = 'NOT_FOUND_EVENT',
  NOT_FOUND_UNIT_LOGO = 'NOT_FOUND_UNIT_LOGO',
  NOT_FOUND_COVER_TEMPLATE = 'NOT_FOUND_COVER_TEMPLATE',

  BAD_REQUEST_GRADE_NAME = 'BAD_REQUEST_GRADE_NAME',
  BAD_REQUEST_STUDENTS = 'BAD_REQUEST_STUDENTS',
  BAD_REQUEST_MULTIPLE_UNITS_ACCESS = 'BAD_REQUEST_MULTIPLE_UNITS_ACCESS',
  BAD_REQUEST_NO_VALID_UNIT_ID = 'BAD_REQUEST_NO_VALID_UNIT_ID',
  BAD_REQUEST_TIMELINE_ORDER = 'BAD_REQUEST_TIMELINE_ORDER',
  BAD_REQUEST_TIMELINE_PAST = 'BAD_REQUEST_TIMELINE_PAST',
  BAD_REQUEST_MISSING_BIOGRAPHY = 'BAD_REQUEST_MISSING_BIOGRAPHY',

  CONFLICT_EXISTING_BOOKS = 'CONFLICT_EXISTING_BOOKS',
  CONFLICT_EVENT_WITH_EXISTING_BOOKS = 'CONFLICT_EVENT_WITH_EXISTING_BOOKS',
  CONFLICT_EVENT_ALREADY_ACTIVE = 'CONFLICT_EVENT_ALREADY_ACTIVE',
  CONFLICT_MORE_THAN_ONE_ACTIVE_EVENT = 'CONFLICT_MORE_THAN_ONE_ACTIVE_EVENT',
  CONFLICT_REMOVE_UNIT_WITH_BOOKS = 'CONFLICT_REMOVE_UNIT_WITH_BOOKS',
  CONFLICT_CHANGE_PAGES_WITH_BOOKS = 'CONFLICT_CHANGE_PAGES_WITH_BOOKS',
  CONFLICT_NO_EXISTING_VALID_UNIT = 'CONFLICT_NO_EXISTING_VALID_UNIT',

  UNAUTHORIZED_USER_NO_ACCESS_TO_UNIT = 'UNAUTHORIZED_USER_NO_ACCESS_TO_UNIT',

  CREATE_PIX_ORDER_FAILED = 'CREATE_PIX_ORDER_FAILED',
  CREATE_CARD_ORDER_FAILED = 'CREATE_CARD_ORDER_FAILED',

  BAD_REQUEST_GRADE_NAME_ALREADY_EXISTS = 'BAD_REQUEST_GRADE_NAME_ALREADY_EXISTS',
  BAD_REQUEST_SCHOOL_USER_WITHOUT_UNITS = 'BAD_REQUEST_SCHOOL_USER_WITHOUT_UNITS',
  BAD_REQUEST_INVALID_ROLE_FOR_USER_CREATION = 'BAD_REQUEST_INVALID_ROLE_FOR_USER_CREATION',
  CONFLICT_EMAIL_ALREADY_EXISTS = 'CONFLICT_EMAIL_ALREADY_EXISTS',
  NOT_FOUND_BOOK_TEMPLATE = 'NOT_FOUND_BOOK_TEMPLATE',
  NOT_FOUND_GRADE = 'NOT_FOUND_GRADE',
  NOT_FOUND_USER = 'NOT_FOUND_USER',
  BAD_REQUEST_CANNOT_DELETE_SELF = 'BAD_REQUEST_CANNOT_DELETE_SELF',

  NOT_FOUND_PDF_CLASS = 'NOT_FOUND_PDF_CLASS',
  NOT_FOUND_PDF_NO_ELIGIBLE_PAGES = 'NOT_FOUND_PDF_NO_ELIGIBLE_PAGES',
  NOT_FOUND_PDF_NO_STUDENTS = 'NOT_FOUND_PDF_NO_STUDENTS',
  NOT_FOUND_PDF_NO_ACTIVE_EVENT = 'NOT_FOUND_PDF_NO_ACTIVE_EVENT',
  NOT_FOUND_PDF_PAGE = 'NOT_FOUND_PDF_PAGE',
  NOT_FOUND_COVER = 'NOT_FOUND_COVER',
  NOT_FOUND_BACK_COVER = 'NOT_FOUND_BACK_COVER',
  BAD_REQUEST_MISSING_COVER_DRAWING = 'BAD_REQUEST_MISSING_COVER_DRAWING',

  BAD_REQUEST_QR_CODE_NOT_READABLE = 'BAD_REQUEST_QR_CODE_NOT_READABLE',
  BAD_REQUEST_DRAW_SQUARE_NOT_FOUND = 'BAD_REQUEST_DRAW_SQUARE_NOT_FOUND',
  BAD_REQUEST_BOOK_TEMPLATE_MISMATCH = 'BAD_REQUEST_BOOK_TEMPLATE_MISMATCH',
  NOT_FOUND_STUDENT = 'NOT_FOUND_STUDENT',
  NOT_FOUND_BOOK_TEMPLATE_PAGE = 'NOT_FOUND_BOOK_TEMPLATE_PAGE',
  NOT_FOUND_ACTIVE_EVENT_FOR_STUDENT = 'NOT_FOUND_ACTIVE_EVENT_FOR_STUDENT',
  INTERNAL_CLOUDFLARE_UPLOAD_FAILED = 'INTERNAL_CLOUDFLARE_UPLOAD_FAILED',
  INTERNAL_GEMINI_RECOGNITION_FAILED = 'INTERNAL_GEMINI_RECOGNITION_FAILED',
  INTERNAL_GOOGLE_CLOUD_VISION_RECOGNITION_FAILED = 'INTERNAL_GOOGLE_CLOUD_VISION_RECOGNITION_FAILED',
  INTERNAL_QR_CODE_RECOGNITION_FAILED = 'INTERNAL_QR_CODE_RECOGNITION_FAILED',

  HTTP_ERROR = 'HTTP_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  INTERNAL_CLOUDFLARE_GET_FILE_FAILED = 'INTERNAL_CLOUDFLARE_GET_FILE_FAILED',

  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}
