export interface ApiError {
  statusCode: number;
  key: ErrorKeys;
  message: string;
  path: string;
  timestamp: string;
  requestId?: string;
  errors?: Array<{ field: string; messages: string[] }>;
}

export enum ErrorKeys {
  BAD_REQUEST_MISSING_GOOGLE_AUTH_TOKEN = 'BAD_REQUEST_MISSING_GOOGLE_AUTH_TOKEN',
  UNAUTHORIZED_INVALID_GOOGLE_CREDENTIALS = 'UNAUTHORIZED_INVALID_GOOGLE_CREDENTIALS',
  UNAUTHORIZED_INVALID_TOKEN = 'UNAUTHORIZED_INVALID_TOKEN',
  UNAUTHORIZED_USER_NOT_FOUND = 'UNAUTHORIZED_USER_NOT_FOUND',
  UNAUTHORIZED_BACKOFFICE_ACCESS = 'UNAUTHORIZED_BACKOFFICE_ACCESS',
  UNAUTHORIZED_INVALID_WEBHOOK_SIGNATURE = 'UNAUTHORIZED_INVALID_WEBHOOK_SIGNATURE',

  FORBIDDEN_MISSING_AUTH_TOKEN = 'FORBIDDEN_MISSING_AUTH_TOKEN',
  FORBIDDEN_INSUFFICIENT_PERMISSIONS = 'FORBIDDEN_INSUFFICIENT_PERMISSIONS',

  NOT_FOUND_BOOK_NOT_FOUND = 'NOT_FOUND_BOOK_NOT_FOUND',
  NOT_FOUND_ORDER = 'NOT_FOUND_ORDER',

  CREATE_PIX_ORDER_FAILED = 'CREATE_PIX_ORDER_FAILED',
  CREATE_CARD_ORDER_FAILED = 'CREATE_CARD_ORDER_FAILED',

  HTTP_ERROR = 'HTTP_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',

  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}
